### ISSUE TITLE
De-couple role from `httpd` requirement?

### ISSUE THREAD

**Issue by decentral1se** [robertdebock/ansible-role-mediawiki#4]
**Describe the bug**
This role depends on a `httpd` installation but not all users will use `httpd`.

**To Reproduce**
1. Check the role `meta/main.yml`

**Expected behavior**
The role can be used with any web server.

**Error**
Handlers will fail if missing the `httpd` role. 

https://github.com/robertdebock/ansible-role-mediawiki/blob/master/tasks/main.yml#L16

**Environment**
- Control node OS: Debian 10
- Control node Ansible version: 2.8.5
- Managed node OS: Debian 10

**Additional context**
I notice `httpd` is in all the places in your roles, so perhaps this is not easy to manage.

**Comment by robertdebock** [comment]
Hi @decentral1se,

This role is indeed hard-linked to `httpd`. Basically to re-use the httpd handler.

Would you have a suggestion how to now hard-link these roles?

**Comment by decentral1se** [comment]
Hey, it's unclear and also it seems like it would mess up your dependency graph too :/

Although, what about:

```yaml
dependencies:
  - { role: httpd, when: foo}
  - { role: nginx, when: bar}
```

That would be a start. Not sure how Ansible then manages the role dependencies?

Then the handler call could be "restart the web server" and not tied directly.
